### ISSUE TITLE
Local updates and plugin installs - "Missing zlib extensions" - OS X 10.9

### ISSUE THREAD

**Issue by shaneholloman** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#1]
All is well running locally except for any update or install functions as seen below

This message below is displayed upon attempting a local install via the wordpress admin

```
   Downloading install package from https://downloads.wordpress.org/plugin/wp-editor.1.2.2.zip…
   Unpacking the package…
   Abort class-pclzip.php : Missing zlib extensions
```

Please note 
1. I have deployed here: https://cycopress.appspot.com/ 
    here are the freshly installed pindom stats: http://tools.pingdom.com/fpt/#!/t0XoQ/https://cycopress.appspot.com/
2. I used your prescribed method for installing mysql
3. I typically use homebrew for local installations for items such as zlib - homebrew confirms zlib is installed, however I realize this particular instance  is probably only effective for the homebrew "cellar" environment.
4. When answering this please assume I am not an expert but decent at following instruction.
- I'm guessing maybe I need to install zlib so GoogleAppEngineLauncher.app can use it too?? If so what is best practice for this?

I greatly appreciate any guidance : )

**Comment by wondarkid** [comment]
I have this same issue on my site <a href="https://www.tecteem.com/toxicwap-movies-free-download/">TECTEEM</a>. I cant seem to install any plugins. Please take a look at my site and give me possible solutions. Here is the direct link to the site https://www.tecteem.com/toxicwap-movies-free-download/

**Comment by wondarkid** [comment]
I have resolved the issue on my site <a href="https://www.tecteem.com/toxicwap-movies-free-download/">TECTEEM</a> or so i think but i can now install plugins. All i did was chat with my hosting provider and after a few minutes later the problem was resolved. There are some method i saw though. It involves you manually going to edit the .php file of your website. Here is a link for the procedure https://solidfoundationwebdev.com/blog/posts/fix-abort-class-pclzip-php-missing-zlib-extensions-in-wordpress. If it works for you please let others know
