### ISSUE TITLE
Cloud SQL Wordpress DB connection always on.

### ISSUE THREAD

**Issue by evilopinions** [GoogleCloudPlatform/appengine-php-wordpress-starter-project#31]
I have just managed to do this basic installation including the Batcache and the Gapp engine plugin.
I just saw that the total usage is 42 hours of the Cloud SQL instance.

My site has no posts and is fairly new.
There are no followers neither visitors.
I am wondering why the SQL is always on ?

**Comment by johndmulhausen** [comment]
This is because of the settings in cron.yaml. If you're not going to make use of cron.yaml for things like scheduled posts, etc, then by all means turn it off or throttle it down to once a day or something.

Another strategy to reduce costs is to use package billing which is $0.36/day and leave cron.yaml cranked up to it's default (run every 15 minutes).
